name: Branch pushed
on:
  push:
    branches:
      - "**"
jobs:
  build:
    name: Build the code
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
      - run: npm install
      - run: npm run build
  unit-test:
    name: Unit test the code
    needs:
      - build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
      - run: npm install
      - run: npm run test:unit
  integration-test:
    name: Integration test the code
    needs:
      - unit-test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.3
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"
      - run: npm install
      - run: npm run test:e2e
